// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itnplqubgwouqakvhxaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bnBscXViZ3dvdXFha3ZoeGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNTM1NTEsImV4cCI6MjA1NDgyOTU1MX0._53K7nLW177fw7D3eAPqawczjxLnDRqZ3sKh53xPmWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);